language: python
os:
- linux
python:
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
before_install:
- pip install mypy flake8
- python static_tests.py
- pip install restructuredtext_lint
- rst-lint README.rst
install: pip install .
script: exit 0
after_script:
- echo "[distutils]\nindex-servers =\n    pypi\n\n" > ~/.pypirc
- echo "[pypi]\nusername:dikunix\npassword:${PYPI_PASSWORD}\n" >> ~/.pypirc
- python setup.py sdist upload
env:
  secure: lxynKL+ebF0aZOc5+DS2Upe2TDdEOZSWJU5Mj+4eDJVxjnDbmvd4BYNd6IXvWyolsbxiJSnoH6Mgh6JKD3afy3BlvwpUXsqN8NEoWYpZDwIoV0n2poBuqiRCsgC9DYBq7rgqZIenmzq3qQoCCK6Gj+0IZ15ymQBt8SEYyxy0LUAXR0RIMTENWs5+xPT5fBLDU28/pGs1c5cmAo5fZJPWvNmnsZFJPoOQ9ZCyanOMugi1VJaZDGIhx7znsF/wYIO+PtJIySoQDhXxG8F+vYJLXp9Y6sWUnt6rtfGW+hWj4Fz2cXVOf9yboWQJCionlanMiUQoWviOPbQ8pT9QFWDBpdnL249u4QUTM/nVy+zjeI9YDqE7DulIPakSWFEd+/9GtozttFIBLctDSxPIwmO6tad8cGyZbLw+E5iuKuoTpE4UGEtIthQEVSKj9FsgWi5Urh6/X5N4XZzcbwH0wElL3LFYPJV7QzeZ3oQBUMjtwFTQLGlHUTqpvWJJUv4YvhXnhxr6X4AmRusUGXQ1EeQ4QpUKkDpVvz4pFxqUAEzuIis7UGNaUm3F/QZdx/7GYNn8ZhuRJuuj1OK0JSG3MsE1rdEGyyi+f48k8FRbk+ZDIf6EFU5q5cI4R1BrK9wz94/PxcNU5dLih6uzzddpkM5I35Jll/jpYTA9VdSpY9IYhWI=
