sudo: required
services:
  - docker
language: python
os:
  - linux
  - osx
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
matrix:
  exclude:
  - os: osx
    python: "3.3"
  - os: osx
    python: "3.4"
  - os: osx
    python: "3.5"
  - os: osx
    python: "3.5-dev"
  - os: osx
    python: "3.6"
before_install:
  - docker pull lbjay/canvas-docker
  - docker run --publish=3000:3000 --detach lbjay/canvas-docker
  - pip install mypy flake8 pytest
  - python static_tests.py
install:
  - pip install .
script:
  - pytest tests/test_courses.py
